[project]
name = "snake-game-deep-q-learning"
version = "0.0.1"
description = "TODO"
authors = ["Wiktor Jurkiewicz <watjurk@gmail.com>", "Nick"]
channels = ["pytorch", "conda-forge"]
platforms = ["osx-arm64", "win-64"]

[tasks]
start = "python ./src/main.py"

[dependencies]
torchaudio = ">=2.3.0,<2.4"
python = "3.10.*"
pytorch = ">=2.3.0,<2.4"
torchvision = ">=0.18.0,<0.19"
numpy = ">=1.26.4,<1.27"
opencv = ">=4.6.0,<4.10"
